/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#736249",
        "inverse-on-surface": "#f3f0ea",
        "on-surface": "#1c1c18",
        "primary-fixed": "#f9ddd1",
        "on-primary": "#ffffff",
        "on-tertiary-fixed-variant": "#5c412a",
        "inverse-primary": "#dcc1b5",
        surface: "#fcf9f3",
        "secondary-fixed-dim": "#dac3a6",
        "on-primary-fixed": "#271811",
        background: "#fcf9f3",
        outline: "#817570",
        "on-secondary": "#ffffff",
        "secondary-container": "#f7dfc0",
        "surface-container-low": "#f6f3ed",
        tertiary: "#2c1805",
        "tertiary-fixed": "#ffdcc1",
        "surface-tint": "#6f5a51",
        "outline-variant": "#d2c3be",
        "tertiary-fixed-dim": "#e5bfa1",
        "on-error-container": "#93000a",
        "surface-dim": "#dcdad4",
        "primary-container": "#3f2e26",
        error: "#ba1a1a",
        "surface-container": "#f0eee8",
        "on-primary-fixed-variant": "#56433a",
        primary: "#281912",
        "on-background": "#1c1c18",
        "on-primary-container": "#ad958a",
        "on-tertiary": "#ffffff",
        "surface-container-highest": "#e5e2dc",
        "surface-container-high": "#ebe8e2",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed-variant": "#54442e",
        "on-tertiary-fixed": "#2b1704",
        "inverse-surface": "#31312d",
        "surface-variant": "#e5e2dc",
        "secondary-fixed": "#f7dfc0",
        "on-surface-variant": "#4f4540",
        secondary: "#6d5c44",
        "surface-bright": "#fcf9f3",
        "on-error": "#ffffff",
        "tertiary-container": "#442d17",
        "primary-fixed-dim": "#dcc1b5",
        "on-tertiary-container": "#b69377",
        "on-secondary-fixed": "#251907",
        "error-container": "#ffdad6",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "gutter-sm": "0.75rem",
        "spacer-sm": "0.5rem",
        "gutter-md": "1rem",
        "spacer-xl": "2.5rem",
        "margin-screen": "1.25rem",
        "spacer-md": "1rem",
        "spacer-xs": "0.25rem",
        "spacer-lg": "1.5rem",
      },
      fontFamily: {
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "headline-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
